/*
* Copyright (C) 2025 Rastislav Kish
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, version 3.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program. If not, see <https://www.gnu.org/licenses/>.
*/

package com.rastislavkish.vscan.core

data class Model(
    val name: String,
    val author: String,
    val family: String,
    val size: String,
    val identifier: String,
    ) {

    companion object {

        val presets=listOf<Model>(
            Model("GPT 5.5",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-5.5",
                ),
            Model("GPT 5.5 Pro",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-5.5-pro",
                ),
            Model("GPT 5.4",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-5.4",
                ),
            Model("GPT 5.4 Mini",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-5.4-mini",
                ),
            Model("GPT 5.4 Nano",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-5.4-nano",
                ),
            Model("GPT 5.4 Pro",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-5.4-pro",
                ),
            Model("GPT 4.1",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-4.1",
                ),
            Model("GPT 4.1-mini",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-4.1-mini",
                ),
            Model("GPT 4.1-nano",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-4.1-nano",
                ),
            Model("GPT 4O",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-4o",
                ),
            Model("GPT 4O mini",
                "OpenAI",
                "GPT",
                "Unknown",
                "vscan-gpt-4o-mini",
                ),
            Model("Claude Opus 4.7",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-opus-4.7",
                ),
            Model("Claude Sonnet 4.6",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-sonnet-4.6",
                ),
            Model("Claude Haiku 4.5",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-haiku-4.5",
                ),
            Model("Claude Opus 4.6",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-opus-4.6",
                ),
            Model("Claude Sonnet 4.5",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-sonnet-4.5",
                ),
            Model("Claude Opus 4.5",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-opus-4.5",
                ),
            Model("Claude 4 Opus",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-4-opus",
                ),
            Model("Claude 4 Sonnet",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-4-sonnet",
                ),
            Model("Claude 3.7 Sonnet",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-3.7-sonnet",
                ),
            Model("Claude 3.5 Sonnet",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-3.5-sonnet",
                ),
            Model("Claude 3.5 Haiku",
                "Anthropic",
                "Claude",
                "Unknown",
                "vscan-claude-3.5-haiku",
                ),
            Model("Gemini 3.1 Pro",
                "Google",
                "Gemini",
                "Unknown",
                "vscan-gemini-3.1-pro",
                ),
            Model("Gemini 3 Flash",
                "Google",
                "Gemini",
                "Unknown",
                "vscan-gemini-3-flash",
                ),
            Model("Gemini 3.1 Flash-Lite",
                "Google",
                "Gemini",
                "Unknown",
                "vscan-gemini-3.1-flash-lite",
                ),
            Model("Gemini 2.5 pro",
                "Google",
                "Gemini",
                "Unknown",
                "vscan-gemini-2.5-pro",
                ),
            Model("Gemini 2.5 flash",
                "Google",
                "Gemini",
                "Unknown",
                "vscan-gemini-2.5-flash",
                ),
            Model("Qwen 3.6 35B A3B",
                "Alibaba",
                "Qwen",
                "35B A3B",
                "vscan-qwen-3.6-35b-a3b",
                ),
            Model("Qwen 3.6 27B",
                "Alibaba",
                "Qwen",
                "27B",
                "vscan-qwen-3.6-27b",
                ),
            Model("Qwen 3.5 397B A17B",
                "Alibaba",
                "Qwen",
                "397B A17B",
                "vscan-qwen-3.5-397b-a17b",
                ),
            Model("Qwen 3.5 122B A10B",
                "Alibaba",
                "Qwen",
                "122B A10B",
                "vscan-qwen-3.5-122b-a10b",
                ),
            Model("Qwen 3.5 35B A3B",
                "Alibaba",
                "Qwen",
                "35B A3B",
                "vscan-qwen-3.5-35b-a3b",
                ),
            Model("Qwen 3.5 27B",
                "Alibaba",
                "Qwen",
                "27B",
                "vscan-qwen-3.5-27b",
                ),
            Model("Qwen 3.5 9B",
                "Alibaba",
                "Qwen",
                "9B",
                "vscan-qwen-3.5-9b",
                ),
            Model("Qwen 3.5 4B",
                "Alibaba",
                "Qwen",
                "4B",
                "vscan-qwen-3.5-4b",
                ),
            Model("Qwen 3.5 2B",
                "Alibaba",
                "Qwen",
                "2B",
                "vscan-qwen-3.5-2b",
                ),
            Model("Qwen 3.5 0.8B",
                "Alibaba",
                "Qwen",
                "0.8B",
                "vscan-qwen-3.5-0.8b",
                ),
            Model("Qwen 2.5 VL 72B",
                "Alibaba",
                "Qwen",
                "72B",
                "vscan-qwen-2.5-vl-72b",
                ),
            Model("Qwen 2.5 VL 32B",
                "Alibaba",
                "Qwen",
                "32B",
                "vscan-qwen-2.5-vl-32b",
                ),
            Model("Gemma 4 31B",
                "Google",
                "Gemma",
                "31B",
                "vscan-gemma-4-31b",
                ),
            Model("Gemma 4 26B A4b",
                "Google",
                "Gemma",
                "26B A4B",
                "vscan-gemma-4-26b-a4b",
                ),
            Model("Gemma 4 E4B",
                "Google",
                "Gemma",
                "E4B",
                "vscan-gemma-4-e4b",
                ),
            Model("Gemma 4 E2B",
                "Google",
                "Gemma",
                "E2B",
                "vscan-gemma-4-e2b",
                ),
            Model("Gemma 3 27B",
                "Google",
                "Gemma",
                "27B",
                "vscan-gemma-3-27b",
                ),
            Model("Gemma 3 12B",
                "Google",
                "Gemma",
                "12B",
                "vscan-gemma-3-12b",
                ),
            Model("Gemma 3 4B",
                "Google",
                "Gemma",
                "4B",
                "vscan-gemma-3-4b",
                ),
            Model("GLM 5V Turbo",
                "Jingsheng Hengxing Technology",
                "GLM",
                "Unknown",
                "vscan-glm-5v-turbo",
                ),
            Model("GLM 4.6V",
                "Jingsheng Hengxing Technology",
                "GLM",
                "106B",
                "vscan-glm-4.6v",
                ),
            Model("GLM 4.6V Flash",
                "Jingsheng Hengxing Technology",
                "GLM",
                "9B",
                "vscan-glm-4.6v-flash",
                ),
            Model("GLM 4.5V",
                "Jingsheng Hengxing Technology",
                "GLM",
                "106B A12B",
                "vscan-glm-4.5v",
                ),
            Model("GLM OCR",
                "Jingsheng Hengxing Technology",
                "GLM",
                "0.9B",
                "vscan-glm-ocr",
                ),
            Model("Mistral Large 3",
                "Mistral",
                "Mistral",
                "675B A41B",
                "vscan-mistral-large-3",
                ),
            Model("Mistral Medium 3.1",
                "Mistral",
                "Mistral",
                "Unknown",
                "vscan-mistral-medium-3.1",
                ),
            Model("Mistral Small 4",
                "Mistral",
                "Mistral",
                "119B A6.5B",
                "vscan-mistral-small-4",
                ),
            Model("Mistral Small 3.2",
                "Mistral",
                "Mistral",
                "24B",
                "vscan-mistral-small-3.2",
                ),
            Model("Mistral OCR 3",
                "Mistral",
                "Mistral",
                "Unknown",
                "vscan-mistral-ocr-3",
                ),
            Model("Ministral 3 14B",
                "Mistral",
                "Ministral",
                "14B",
                "vscan-ministral-3-14b",
                ),
            Model("Ministral 3 8B",
                "Mistral",
                "Ministral",
                "8B",
                "vscan-ministral-3-8b",
                ),
            Model("Ministral 3 3B",
                "Mistral",
                "Ministral",
                "3B",
                "vscan-ministral-3-3b",
                ),
            Model("Magistral Medium 1.2",
                "Mistral",
                "Magistral",
                "Unknown",
                "vscan-magistral-medium-1.2",
                ),
            Model("Magistral Small 1.2",
                "Mistral",
                "Magistral",
                "24B",
                "vscan-magistral-small-1.2",
                ),
            Model("Llama 4 Maverick",
                "Meta",
                "Llama",
                "400B A17B",
                "vscan-llama-4-maverick",
                ),
            Model("Llama 4 Scout",
                "Meta",
                "Llama",
                "109B A17B",
                "vscan-llama-4-scout",
                ),
            Model("Molmo 72B",
                "Allen AI",
                "Molmo",
                "72B",
                "vscan-molmo-72b",
                ),
            Model("Molmo 7B D",
                "Allen AI",
                "Molmo",
                "7B",
                "vscan-molmo-7b-d",
                ),
            Model("Molmo 7B O",
                "Allen AI",
                "Molmo",
                "7B",
                "vscan-molmo-7b-o",
                ),
            Model("InternVL 3.5 241B A28B",
                "OpenGVLab",
                "InternVL",
                "241B A28B",
                "vscan-internvl-3.5-241b-a28b",
                ),
            Model("InternVL 3.5 38B",
                "OpenGVLab",
                "InternVL",
                "38B",
                "vscan-internvl-3.5-38b",
                ),
            Model("InternVL 3.5 30B A3B",
                "OpenGVLab",
                "InternVL",
                "30B A3B",
                "vscan-internvl-3.5-30b-a3b",
                ),
            Model("InternVL 3.5 20B A4B",
                "OpenGVLab",
                "InternVL",
                "20B A4B",
                "vscan-internvl-3.5-20b-a4b",
                ),
            Model("InternVL 3.5 14B",
                "OpenGVLab",
                "InternVL",
                "14B",
                "vscan-internvl-3.5-14b",
                ),
            Model("InternVL 3.5 8B",
                "OpenGVLab",
                "InternVL",
                "8B",
                "vscan-internvl-3.5-8b",
                ),
            Model("InternVL 3.5 4B",
                "OpenGVLab",
                "InternVL",
                "4B",
                "vscan-internvl-3.5-4b",
                ),
            Model("InternVL 3.5 2B",
                "OpenGVLab",
                "InternVL",
                "2B",
                "vscan-internvl-3.5-2b",
                ),
            Model("InternVL 3.5 1B",
                "OpenGVLab",
                "InternVL",
                "1B",
                "vscan-internvl-3.5-1b",
                ),
            Model("InternVL 3 78B",
                "OpenGVLab",
                "InternVL",
                "78B",
                "vscan-internvl-3-78b",
                ),
            Model("InternVL 3 14B",
                "OpenGVLab",
                "InternVL",
                "14B",
                "vscan-internvl-3-14b",
                ),
            Model("InternVL 3 2B",
                "OpenGVLab",
                "InternVL",
                "2B",
                "vscan-internvl-3-2b",
                ),
            )

        private val idToModelMap: Map<String, Model>
        init {
            val map=mutableMapOf<String, Model>()

            for (model in presets)
            map.put(model.identifier, model)

            idToModelMap=map
            }

        fun idToName(id: String): String {
            if (!id.startsWith("vscan-"))
            return id

            val model=idToModelMap.get(id)

            return if (model!=null)
            model.name
            else
            id
            }

        fun idToKnownModel(id: String): Model? {
            if (!id.startsWith("vscan-"))
            return null

            return idToModelMap.get(id)
            }

        fun idToModel(id: String): Model
        = idToKnownModel(id) ?: Model(id,
            "unknown",
            "Unknown",
            "Unknown",
            id,
            )

        }
    }
